version: "3.8"
services:
  frontend:
    build: 
      context: './frontend'
      dockerfile: Dockerfile.development
    container_name: frontend
    volumes:
      - ./frontend/src:/app/frontend/src
      - ./frontend/public:/app/frontend/public
    ports:
      - "3000:3000"

  backend:
    build: './backend'
    container_name: backend
    volumes:
      - ./:/app
    ports:
      - "8000:8000"
    env_file:
      - backend/secrets.env.development
    env:
      - MONGO_DB_CONNECTION_STRING=http://mongo:27017
    restart: on-failure
  
  mongo:
    image: mongo
    container_name: mongo
    volumes:
      - ./db:/data/db
    ports:
      - "27017:27017"
