version: "3.8"
services:
  frontend:
    build: 
      context: './frontend'
      dockerfile: Dockerfile.production
    container_name: frontend
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
    ports:
      - "443:443"

  backend:
    build: './backend'
    container_name: backend
    env_file:
      - backend/secrets.env.production
    ports:
      - "8000:8000"
    restart: on-failure
  
  keycloak:
    image: quay.io/keycloak/keycloak:20.0.3
    container_name: keycloak
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    ports:
      - "8080:8080"
    command:
      - start-dev

  keycloak_configure:
    build: './keycloak'
    container_name: keycloak_configure
    restart: on-failure
    environment:
      - frontend=http://localhost