version: "3.8"
services:
  frontend:
    build:
      context: "./frontend"
      dockerfile: Dockerfile.development
    container_name: frontend
    volumes:
      - ./frontend/src:/app/frontend/src
      - ./frontend/public:/app/frontend/public
    ports:
      - "3000:3000"

  backend:
    build: "./backend"
    container_name: backend
    volumes:
      - ./:/app
    ports:
      - "8000:8000"
    environment:
      - MONGO_DB_CONNECTION_STRING=mongodb://mongo:27017
      - AUTH_SECRET_KEY=09d25e094faa6ca2556c818166b7a9563b93f7099f6f0f4caa6cf63b88e8d3e7
    env_file:
      - backend/secrets.env.development
    restart: on-failure

  mongo:
    image: mongo
    container_name: mongo
    volumes:
      - ./db:/data/db
    ports:
      - "27017:27017"
