version: "3.8"
services:
  budget-app-frontend:
    build: './frontend'
    volumes:
      - ./frontend/src:/app/frontend/src
      - ./frontend/public:/app/frontend/public
      - /app/frontend/node_modules
    ports:
      - "3000:3000"
