version: "3.8"
services:
  budget-app-frontend:
    build: 
      context: './frontend'
      dockerfile: Dockerfile.production
    container_name: budget_app_frontend
    volumes:
      - ./frontend/src:/app/frontend/src
      - ./frontend/public:/app/frontend/public
      - /etc/letsencrypt:/etc/letsencrypt
    ports:
      - "443:443"

  budget-app-backend:
    build: './backend'
    container_name: budget_app_backend
    volumes:
      - ./:/app
    ports:
      - "8000:8000"
    restart: on-failure
  
  mongo:
    image: mongo
    container_name: budget_app_mongo
    volumes:
      - ./db:/data/db
    ports:
      - "27017:27017"
  
  keycloak:
    image: quay.io/keycloak/keycloak:20.0.3
    container_name: budget_app_keycloak
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    ports:
      - "8080:8080"
    command:
      - start-dev
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/auth/"]
      interval: 5s
      timeout: 2s
      retries: 15

  keycloak_configure:
    build: './keycloak'
    restart: on-failure
    environment:
      - frontend=http://localhost