name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build
        run: |
          # docker compose -f docker-compose.production.yml build
          # docker compose -f docker-compose.production.yml push
          ls -la
      - name: Deploy
        env:
          KEYCLOAK_DB_NAME: ${{ secrets.KEYCLOAK_DB_NAME }}
          POSTGRES_DB_URL: ${{ secrets.POSTGRES_DB_URL }}
          POSTGRES_DB_PORT: ${{ secrets.POSTGRES_DB_PORT }}
          HOSTNAME: ${{ secrets.HOSTNAME }}
          POSTGRES_DB_USERNAME: ${{ secrets.POSTGRES_DB_USERNAME }}
          POSTGRES_DB_PASSWORD: ${{ secrets.POSTGRES_DB_PASSWORD }}
          KEYCLOAK_ADMIN: ${{ secrets.KEYCLOAK_ADMIN }}
          KEYCLOAK_PASSWORD: ${{ secrets.KEYCLOAK_PASSWORD }}
          NORDIGEN_SECRET_ID: ${{ secrets.NORDIGEN_SECRET_ID }}
          NORDIGEN_SECRET_KEY: ${{ secrets.NORDIGEN_SECRET_KEY }}
          MONGO_DB_USER: ${{ secrets.MONGO_DB_USER }}
          MONGO_DB_PASSWORD: ${{ secrets.MONGO_DB_PASSWORD }}
          MONGO_DB_URL: ${{ secrets.MONGO_DB_URL }}
          EC2_USER: ${{ secrets.EC2_USER }}
          EC2_HOSTNAME: ${{ secrets.EC2_HOSTNAME }}
          EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
        run: |
          echo "$EC2_SSH_KEY" > private_key && chmod 600 private_key
          echo "KEYCLOAK_DB_NAME=$KEYCLOAK_DB_NAME" >> .env
          echo "POSTGRES_DB_URL=$POSTGRES_DB_URL" >> .env
          echo "POSTGRES_DB_PORT=$POSTGRES_DB_PORT" >> .env
          echo "HOSTNAME=$HOSTNAME" >> .env
          echo "POSTGRES_DB_USERNAME=$POSTGRES_DB_USERNAME" >> .env
          echo "POSTGRES_DB_PASSWORD=$POSTGRES_DB_PASSWORD" >> .env
          echo "KEYCLOAK_ADMIN=$KEYCLOAK_ADMIN" >> .env
          echo "KEYCLOAK_PASSWORD=$KEYCLOAK_PASSWORD" >> .env
          echo "NORDIGEN_SECRET_ID=$NORDIGEN_SECRET_ID" >> .env
          echo "NORDIGEN_SECRET_KEY=$NORDIGEN_SECRET_KEY" >> .env
          echo "MONGO_DB_USER=$MONGO_DB_USER" >> .env
          echo "MONGO_DB_PASSWORD=$MONGO_DB_PASSWORD" >> .env
          echo "MONGO_DB_URL=$MONGO_DB_URL" >> .env
          scp -o StrictHostKeyChecking=no -i private_key scripts/pre_deploy.sh ${EC2_USER}@${EC2_HOSTNAME}:/home/ubuntu
          ssh -o StrictHostKeyChecking=no -i private_key ${EC2_USER}@${EC2_HOSTNAME} '
            chmod u+rx pre_deploy.sh &&
            ./pre_deploy.sh
          '
          scp -o StrictHostKeyChecking=no -i private_key scripts/deploy.sh ${EC2_USER}@${EC2_HOSTNAME}:/home/ubuntu
          scp -o StrictHostKeyChecking=no -i private_key -r ./* ${EC2_USER}@${EC2_HOSTNAME}:/home/ubuntu/budget_app
          scp -o StrictHostKeyChecking=no -i private_key .env ${EC2_USER}@${EC2_HOSTNAME}:/home/ubuntu/budget_app
          ssh -o StrictHostKeyChecking=no -i private_key ${EC2_USER}@${EC2_HOSTNAME} '
            chmod u+rx deploy.sh &&
            ./deploy.sh
          '
